<a href="https://colab.research.google.com/github/ChanggonSong/PyTorch-Tutorials/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import torch
import numpy as np

##텐서(tensor) 초기화

- 데이터로부터 직접 Tensors를 생성하기

In [20]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

- NumPy 배열로부터 Tensors 생성하기 (그 반대도 가능) - NumPy 변환(Bridge)

In [21]:
np_array = np.array(data)
print(np_array)

print()

x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]

tensor([[1, 2],
        [3, 4]])


- 다른 텐서로부터 생성하기

In [22]:
# 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다. 1로 채우기
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다. 실수형, 랜덤으로 채우기
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7229, 0.4883],
        [0.9217, 0.6660]]) 



- 무작위(random) 또는 상수(constant) 값을 사용하기
  - shape 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.

In [23]:
shape = (2,3,) # output tensor를 2x3으로.
rand_tensor = torch.rand(shape) # 랜덤으로 채우기
ones_tensor = torch.ones(shape) # 1로 채우기
zeros_tensor = torch.zeros(shape) # 0으로 채우기

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3044, 0.3233, 0.9318],
        [0.4781, 0.1676, 0.0194]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


##텐서의 속성(Attribute)

- 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냅니다.

In [24]:
tensor = torch.rand(3,4) # output tensor의 shape 사이즈를 결정

print(f"Shape of tensor: {tensor.shape}") # 텐서의 모양(shape)
print(f"Datatype of tensor: {tensor.dtype}") # 자료형(datatype)
print(f"Device tensor is stored on: {tensor.device}") # 어느 장치에 저장되는지

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서 연산(Operation)

- 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등 100가지 이상의 텐서 연산들: https://pytorch.org/docs/stable/torch.html
- 각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수 있음

- 기본적으로 텐서는 CPU에 생성됩니다. .to 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있다. 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하세요!

In [ ]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

- NumPy식의 표준 인덱싱과 슬라이싱:

In [27]:
tensor = torch.ones(4, 4) # 4x4 output tensor 1로 채우기
print(f"First row: {tensor[0]}") # 첫번째 row(열) 출력: (0,0), (0,1), (0,2), ...
print(f"First column: {tensor[:, 0]}") # 첫번째 column(행) 출력: (0,0), (1,0), (2,0), ...
print(f"Last column: {tensor[..., -1]}") # 마지막 column(행) 출력: (0, 마지막), (1, 마지막), ...
tensor[:,1] = 0 # 두번째 행을 모두 0으로. (0,1), (1,1), (2,1), ...
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


- Joining tensors: `torch.cat` 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있다. `torch.cat` 과 미묘하게 다른 또 다른 텐서 결합 연산인 **torch.stack** 도 참고하기.

In [28]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


- 산술 연산(Arithmetic operations)

In [44]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# ``tensor.T`` 는 텐서의 전치(transpose)를 반환합니다.
print(tensor)
print(tensor.T)
print()

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

- Single-element tensors (단일-요소 텐서): 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, `item()` 을 사용하여 Python 숫자 값으로 변환할 수 있습니다:

In [47]:
print(tensor)

agg = tensor.sum()
print(agg)

agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor(12.)
12.0 <class 'float'>


- In-place operations(바꿔치기 연산):  연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, `_` 접미사를 갖습니다. 예를 들어: `x.copy_(y)` 나 `x.t_()` 는 `x` 를 변경합니다.

In [48]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


##NumPy 변환(Bridge)

####텐서를 NumPy 배열로 변환하기

In [49]:
t = torch.ones(5) # 텐서
print(f"t: {t}")

n = t.numpy() # NumPy 배열로 변환
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


- 텐서의 변경 사항이 NumPy 배열에 반영됩니다.

In [51]:
t.add_(1) # 1을 더함
print(f"t: {t}")

print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


####NumPy 배열을 텐서로 변환하기

In [54]:
n = np.ones(5) # NumPy 배열
t = torch.from_numpy(n) # 텐서로 변환

- NumPy 배열의 변경 사항이 텐서에 반영됩니다.

In [55]:
np.add(n, 1, out=n)
print(f"t: {t}")

print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
